function modified
dzgierski19/getRandomPhoneNumber pull request #1
Opened 2023-03-24 18:36 UTC by dzgierski19

2023-03-24 19:11 UTC, mwakulinski requested changes

2023-03-24 19:11 UTC, mwakulinski commented on getRandomPhoneNumber.js
> +  console.log(randomNineDigits);
RC: remove unnecessary console.log

2023-03-24 20:18 UTC, dzgierski19 commented on getRandomPhoneNumber.js
> +  console.log(randomNineDigits);
console.log deleted

2023-03-26 11:28 UTC, mwakulinski approved these changes
Nice job 💪

2023-03-27 21:04 UTC, merged